# Copyright 2023 Jimmi Dyson.
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ "{{" }} template "chart.name" . {{ "}}" }}-webhook-tls
  namespace: {{ "{{" }} .Release.Namespace {{ "}}" }}
  labels:
    {{ "{{" }}- include "chart.labels" . | nindent 4 {{ "}}" }}
spec:
  dnsNames:
    - {{ "{{" }} template "chart.name" . {{ "}}" }}-webhook.{{ "{{" }} .Release.Namespace {{ "}}" }}.svc
    - {{ "{{" }} template "chart.name" . {{ "}}" }}-webhook.{{ "{{" }} .Release.Namespace {{ "}}" }}.svc.cluster.local
  issuerRef:
    kind: {{ "{{" }} .Values.certificates.issuer.kind {{ "}}" }}
    name: {{ "{{" }} template "chart.issuerName" . {{ "}}" }}
  secretName: {{ "{{" }} template "chart.name" . {{ "}}" }}-webhook-tls
