# Copyright 2023 Jimmi Dyson.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  annotations:
    {{ "{{" }}- with .Values.service.annotations {{ "}}" }}
    {{ "{{" }} toYaml . | nindent 4 {{ "}}" }}
    {{ "{{" }}- end {{ "}}" }}
  labels:
    {{ "{{" }}- include "chart.labels" . | nindent 4 {{ "}}" }}
  name: {{ "{{" }} template "chart.name" . {{ "}}" }}-webhook
  namespace: {{ "{{" }} .Release.Namespace {{ "}}" }}
spec:
  type: {{ "{{" }}.Values.service.type{{ "}}" }}
  ports:
  - name: https
    port: {{ "{{" }} .Values.service.port {{ "}}" }}
    protocol: TCP
    targetPort: webhook
    {{ "{{" }}- if and .Values.service.nodePort (eq "NodePort" .Values.service.type) {{ "}}" }}
    nodePort: {{ "{{" }} .Values.service.nodePort {{ "}}" }}
    {{ "{{" }}- end {{ "}}" }}
  selector:
    {{ "{{" }}- include "chart.selectorLabels" . | nindent 4 {{ "}}" }}
