# Copyright 2023 Jimmi Dyson.
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ "{{" }} template "chart.name" . {{ "}}" }}-webhook
      namespace: system
      path: /mutate-dummy-example-com-v1alpha1-dummy
  failurePolicy: Fail
  name: mdummy.kb.io
  rules:
  - apiGroups:
    - dummy.example.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dummies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ "{{" }} template "chart.name" . {{ "}}" }}-webhook
      namespace: system
      path: /validate-dummy-example-com-v1alpha1-dummy
  failurePolicy: Fail
  name: vdummy.kb.io
  rules:
  - apiGroups:
    - dummy.example.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dummies
  sideEffects: None
