# Copyright 2023 Jimmi Dyson.
# SPDX-License-Identifier: Apache-2.0

name: release-please-main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v4.1
        id: release-please
        with:
          release-type: go
          package-name: {{project-name}}
          pull-request-title-pattern: "build${scope}: release${component} ${version}"
          changelog-notes-type: github

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Run release workflow
        uses: benc-uk/workflow-dispatch@v121
        with:
          workflow: release-tag.yaml
          ref: ${{ steps.release-please.outputs.tag_name }}
