# Copyright 2021-2023 Jimmi Dyson.
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  release-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.6.0
        with:
          enable-cache: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: devbox run -- make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          app_version: ${{ github.ref_name }}
          chart_version: ${{ github.ref_name }}
          target_dir: repo
